### PR TITLE
Add support for generating frames concurrently using a worker pool

### PR DESCRIPTION
**Pull request by marcoshuck**
Just a minor improvement to the generation algorithm to reduce the amount of time it takes to generate and render frame images by introducing a worker pool.

It generates the frames in a random order using all the available CPUs instead of running one frame at a time

Might require some more testing

One thing I noticed is that the message saying that the image was saved is usually sent after the new job has been scheduled, which might be a bit misleading.

### CODE REVIEW

**Comment by manzato** [comment]
Nice! I'll test it tomorrow to see how this performs when there is a GPU involved. I recall trying something similar running parallel process and the performance actually was reduced.

**Comment by marcoshuck** [comment]
> Nice! I'll test it tomorrow to see how this performs when there is a GPU involved. I recall trying something similar running parallel process and the performance actually was reduced.

Nice to know! It might be a good idea to add some sort of benchmark tool to compare results 🤔

**Comment by marcoshuck** [comment]
https://stackoverflow.com/a/5544739 I'll give this a try tomorrow

**Comment by manzato** [comment]
I ran the following command:

`time poetry run chess2vid -i './resources/games/short.pgn' --frame-width=480 --frame-height=240 --blender-bin "/home/manzato/projects/tools/blender-4.2.1-linux-x64/blender" --save-blender short.blend -o ./short_frames -r 1:16`

In this branch:
```
real	0m30.581s
user	0m32.770s
sys	2m20.394s
```

In main:
```
real	0m32.765s
user	0m9.175s
sys	0m10.235s
```

So, slightly better with this code.

**Comment by manzato** [comment]
Bigger frames and 32 frames:

`time poetry run chess2vid -i './resources/games/short.pgn' --frame-width=1024 --frame-height=768 --blender-bin "/home/manzato/projects/tools/blender-4.2.1-linux-x64/blender" --save-blender short.blend -o ./short_frames -r 1:32`

this branch:
```
real	2m17.553s
user	2m21.491s
sys	13m33.808s
```
main:
```
real	2m29.541s
user	0m29.332s
sys	0m47.815s
```

Again, a slight improvement

**Comment by marcoshuck** [comment]
Still not substantial considering that it's using all the available CPUs (much more resource consumption), but happy to know it improved the performance at least a bit.

**Comment by manzato** [comment]
`time poetry run chess2vid -i './resources/games/short.pgn' --frame-width=1920 --frame-height=1080 --blender-bin /home/manzato/projects/tools/blender-4.2.1-linux-x64/blender --save-blender short.blend -o ./short_frames -r 1:64`

this branch:
```
real	11m46.397s
user	12m16.346s
sys	78m16.331s
```

main:
```
real	12m27.956s
user	1m59.109s
sys	3m55.365s
```

**Comment by manzato** [comment]
`time poetry run chess2vid -i './resources/games/short.pgn' --frame-width=1920 --frame-height=1080 --blender-bin /home/manzato/projects/tools/blender-4.2.1-linux-x64/blender --save-blender short.blend -o ./short_frames -r 1:128`

this branch:
```
real	24m39.588s
user	24m49.849s
sys	161m42.463s
```

main:
```
real	25m45.965s
user	3m52.685s
sys	8m9.120s
```

**Comment by marcoshuck** [comment]
I'll keep on investigating the performance issue, but happy to see we saved 1 minute in that last run.

**Pull request merged**
